/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _rootDRouteImport } from './routes/__root.d'

const _rootDRoute = _rootDRouteImport.update({
  id: '/__root/d',
  path: '/d',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/d': typeof _rootDRoute
}
export interface FileRoutesByTo {
  '/d': typeof _rootDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__root/d': typeof _rootDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/d'
  fileRoutesByTo: FileRoutesByTo
  to: '/d'
  id: '__root__' | '/__root/d'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _rootDRoute: typeof _rootDRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root/d': {
      id: '/__root/d'
      path: '/d'
      fullPath: '/d'
      preLoaderRoute: typeof _rootDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  _rootDRoute: _rootDRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
